[package]
name = "imstr"
version = "0.1.0"
edition = "2021"
description = "Immutable string"
documentation = "https://docs.rs/imstr"
repository = "https://github.com/xbfs/imstr"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
license = "MIT"

[dependencies]
serde = { version = "1.0.159", optional = true }

[features]
debug-internal = []
serde = ["dep:serde"]
